development:
  adapter: postgresql
  encoding: unicode
  database: ache_facil_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ache_facil_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  host: 186.202.152.24
  database: babycho1
  username: babycho1
  password: pastelFrango13
  pool: 5
