development: &default
  adapter: postgresql
  encoding: unicode
  database: ache_facil_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: ache_facil_test

production:
  <<: *default
  host: 186.202.152.24
  database: babycho1
  username: babycho1
  password: pastelFrango13
